apiVersion: v1
kind: Service
metadata:
  name: engine-service
  labels:
    app: engine-service
    component: game-engine
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: engine-service
  sessionAffinity: None


